# ============================================================================
#
# The configuration produced by default is meant to highlight the features
# that Zensical provides and to serve as a starting point for your own
# projects.
#
# ============================================================================

[project]
site_name = "Pixelverse"
site_description = "Cloud Native Tooling to generate and process pixelwise geospatial embeddings."
site_author = "Development Seed"
site_url = "https://developmentseed.org/pixelverse/"
repo_name = "developmentseed/pixelverse"
repo_url = "https://github.com/developmentseed/pixelverse/"
nav = [
  { "Home" = "index.md" },
  { "API Reference" = "apiref.md" },
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
favicon = "https://github.com/developmentseed.png?size=32"
language = "en"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "header.autohide",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color # schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "deep orange"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "deep orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
# ----------------------------------------------------------------------------
# In the "font" subsection you can configure the fonts used. By default, fonts
# are loaded from Google Fonts, giving you a wide range of choices from a set
# of suitably licensed fonts. There are options for a normal text font and for
# a monospaced font used in code blocks.
# ----------------------------------------------------------------------------
# [project.theme.font]
text = "Roboto"
code = "Roboto Mono"

# ----------------------------------------------------------------------------
# You can configure your own logo to be shown in the header using the "logo"
# option in the "icons" subsection. The logo can be a path to a file in your
# "docs_dir" or it can be a path to an icon.
#
# Likewise, you can customize the logo used for the repository section of the
# header. Zensical derives the default logo for this from the repository URL.
# See below...
#
# There are other icons you can customize. See the documentation for details.
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://zensical.org/docs/authoring/icons-emojis/#search
# ----------------------------------------------------------------------------
[project.theme.icon]
logo = "lucide/earth"
repo = "fontawesome/brands/github"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/developmentseed"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/development-seed"

[[project.extra.social]]
icon = "fontawesome/solid/paper-plane"
link = "mailto:<info@developmentseed.org>"

# ----------------------------------------------------------------------------
# The "extensions" and "plugins" sections contains even more settings.
# ----------------------------------------------------------------------------

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://corteva.github.io/rioxarray/latest/objects.inv",
  "https://docs.python.org/3/objects.inv",
  "https://docs.xarray.dev/en/latest/objects.inv",
]
paths = ["src/pixelverse"]

[project.plugins.mkdocstrings.handlers.python.options]
# General
show_source = true
# Heading
heading_level = 3
show_root_heading = true
show_symbol_type_heading = true
show_symbol_type_toc = true
# Members
inherited_members = true
# Docstrings
docstring_style = "numpy"
docstring_section_style = "table"
# Signatures
annotations_path = "full"
separate_signature = true
signature_crossrefs = true
show_signature_annotations = true
