name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1
        with:
            enable-cache: true
            python-version: 3.13
      - run: uv run --all-extras --dev pytest -vvv --cov=src
      - name: Report Coverage
        run: uv run --all-extras --dev coverage report -m

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1
        with:
            enable-cache: true
            python-version: 3.13
      - name: Run prek
        run: uv run --all-extras --dev prek run --all-files -v
